/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function MyName(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/myname.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="text"
          castShadow
          receiveShadow
          geometry={nodes.text.geometry}
          material={nodes.text.material}
          position={[-5, 2, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/myname.glb");
